version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/Los_Angeles"
    # Group all GitHub Actions updates into a single PR
    groups:
      github-actions:
        patterns:
          - "*"
    # Add labels to PRs
    labels:
      - "dependencies"
      - "github-actions"
    # Set commit message prefix
    commit-message:
      prefix: "chore"
      include: "scope"